# Generated by Django 4.2.5 on 2023-09-14 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0003_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='issuer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='icomments', to=settings.AUTH_USER_MODEL),
        ),
    ]
