# Generated by Django 4.2.5 on 2023-09-15 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0004_alter_comment_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Normal User', 'Normal User'), ('L1 User', 'L1 User'), ('L2 User', 'L2 User'), ('L3 User', 'L3 User')], default='Normal User', max_length=11),
        ),
    ]
