# Generated by Django 4.2.5 on 2023-09-15 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0006_alter_ticket_ticket_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='ticket_id',
            new_name='ticket_ref',
        ),
    ]
