# Generated by Django 4.2.5 on 2023-09-15 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0007_rename_ticket_id_ticket_ticket_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolved_by',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
